sudo: false
language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
script: yarn build
cache:
  yarn: true
node_js:
  - "8"
branches:
  only:
  - master
